import {
  cilArrowRight,
  cilBan,
  cilCalendar,
  cilCalendarCheck,
  cilCheck,
  cilCheckCircle,
  cilCode,
  cilGroup,
  cilLocationPin,
  cilPeople,
  cilPencil,
  cilPlus,
  cilReload,
  cilSave,
  cilSpeedometer,
  cilTrash,
  cilX,
} from '@coreui/icons';

export const appIcons = {
  activate: cilCheckCircle,
  add: cilPlus,
  arrowRight: cilArrowRight,
  cancel: cilX,
  candidates: cilPeople,
  committee: cilGroup,
  confirm: cilCheck,
  deactivate: cilBan,
  delete: cilTrash,
  documentation: cilCode,
  edit: cilPencil,
  locations: cilLocationPin,
  overview: cilSpeedometer,
  planning: cilCalendar,
  proposal: cilCalendarCheck,
  reload: cilReload,
  save: cilSave,
} as const;
