import {
  Archive as LucideArchive,
  ArrowRight as LucideArrowRight,
  Ban as LucideBan,
  CalendarCheck as LucideCalendarCheck,
  CalendarDays as LucideCalendarDays,
  Check as LucideCheck,
  CircleCheck as LucideCircleCheck,
  Code2 as LucideCode2,
  GraduationCap as LucideGraduationCap,
  LayoutDashboard as LucideLayoutDashboard,
  MapPin as LucideMapPin,
  Menu as LucideMenu,
  Pencil as LucidePencil,
  Plus as LucidePlus,
  RefreshCw as LucideRefreshCw,
  Save as LucideSave,
  Trash2 as LucideTrash2,
  UsersRound as LucideUsersRound,
  X as LucideX,
} from 'lucide';

// The semantic names are stable; the mapping is documented in brand/icon-contract.json.
export const appIcons = {
  activate: LucideCircleCheck,
  add: LucidePlus,
  archive: LucideArchive,
  arrowRight: LucideArrowRight,
  cancel: LucideX,
  calendar: LucideCalendarDays,
  candidates: LucideGraduationCap,
  committee: LucideUsersRound,
  confirm: LucideCheck,
  deactivate: LucideBan,
  delete: LucideTrash2,
  documentation: LucideCode2,
  edit: LucidePencil,
  locations: LucideMapPin,
  menu: LucideMenu,
  overview: LucideLayoutDashboard,
  planning: LucideCalendarDays,
  proposal: LucideCalendarCheck,
  reload: LucideRefreshCw,
  save: LucideSave,
} as const;
