// Generated by fixtures/generate.py. Do not edit directly.
export const syntheticFixtures = {
  "version": 3,
  "revision": "athens-theater-venues-v3",
  "fixtureRoot": "name.papaspyrou.repertoire.lzug.fixture",
  "demoMatrixVersion": "demo-paths-v8",
  "keys": {
    "organizations": {},
    "committees": {
      "name.papaspyrou.repertoire.lzug.fixture.committee.athen": 1,
      "name.papaspyrou.repertoire.lzug.fixture.committee.feenwald": 2
    },
    "persons": {
      "name.papaspyrou.repertoire.lzug.fixture.person.chair.athen": 1,
      "name.papaspyrou.repertoire.lzug.fixture.person.deputy.athen": 2,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.absent": 3,
      "name.papaspyrou.repertoire.lzug.fixture.person.crosscommittee": 4,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.fallback": 5,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.replacement": 6,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.unsuitable": 7,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.reserve": 8,
      "name.papaspyrou.repertoire.lzug.fixture.person.chair.feenwald": 9,
      "name.papaspyrou.repertoire.lzug.fixture.person.deputy.feenwald": 10
    },
    "memberships": {
      "name.papaspyrou.repertoire.lzug.fixture.membership.chair.athen": 1,
      "name.papaspyrou.repertoire.lzug.fixture.membership.deputy.athen": 2,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.absent": 3,
      "name.papaspyrou.repertoire.lzug.fixture.membership.crosscommittee.athen": 4,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.fallback": 5,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.replacement": 6,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.unsuitable": 7,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.reserve": 8,
      "name.papaspyrou.repertoire.lzug.fixture.membership.chair.feenwald": 9,
      "name.papaspyrou.repertoire.lzug.fixture.membership.deputy.feenwald": 10,
      "name.papaspyrou.repertoire.lzug.fixture.membership.crosscommittee.feenwald": 11
    },
    "accounts": {
      "name.papaspyrou.repertoire.lzug.fixture.account.chair": 1,
      "name.papaspyrou.repertoire.lzug.fixture.account.examiner": 2,
      "name.papaspyrou.repertoire.lzug.fixture.account.deputy": 3,
      "name.papaspyrou.repertoire.lzug.fixture.account.replacement": 4
    },
    "locations": {
      "name.papaspyrou.repertoire.lzug.fixture.location.global.zappeion": 1,
      "name.papaspyrou.repertoire.lzug.fixture.location.committee.athen.gazi": 2,
      "name.papaspyrou.repertoire.lzug.fixture.location.committee.feenwald.nationalgarden": 3
    },
    "rooms": {
      "name.papaspyrou.repertoire.lzug.fixture.room.zappeion.theseus": 1,
      "name.papaspyrou.repertoire.lzug.fixture.room.gazi.handwerkerensemble": 2,
      "name.papaspyrou.repertoire.lzug.fixture.room.nationalgarden.oberon": 3,
      "name.papaspyrou.repertoire.lzug.fixture.room.zappeion.hippolyta": 4,
      "name.papaspyrou.repertoire.lzug.fixture.room.gazi.pyramus": 5,
      "name.papaspyrou.repertoire.lzug.fixture.room.nationalgarden.titania": 6
    },
    "location_contacts": {
      "name.papaspyrou.repertoire.lzug.fixture.location-contact.zappeion.hippolyta": 1,
      "name.papaspyrou.repertoire.lzug.fixture.location-contact.gazi.quince": 2
    },
    "candidates": {
      "name.papaspyrou.repertoire.lzug.fixture.candidate.planchange": 1,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.absence": 2,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.lysander": 3,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.demetrius": 4,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.egeus": 5,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.philostrate": 6,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.peaseblossom": 7,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.cobweb": 8,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.moth": 9,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.mustardseed": 10,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.moonshine": 11,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.lion": 12
    }
  },
  "demoRoles": {
    "chair": {
      "account_id": 1,
      "person_id": 1,
      "committee_member_id": 1,
      "first_name": "Theseus",
      "last_name": "von Athen",
      "display_name": "Theseus von Athen",
      "account_email": "chair@demo.lzug.invalid",
      "person_email": "theseus.athen@demo.lzug.invalid",
      "fixture_key": "name.papaspyrou.repertoire.lzug.fixture.person.chair.athen"
    },
    "examiner": {
      "account_id": 2,
      "person_id": 3,
      "committee_member_id": 3,
      "first_name": "Peter",
      "last_name": "Quince",
      "display_name": "Peter Quince",
      "account_email": "examiner@demo.lzug.invalid",
      "person_email": "peter.quince@demo.lzug.invalid",
      "fixture_key": "name.papaspyrou.repertoire.lzug.fixture.person.examiner.absent"
    },
    "replacement": {
      "account_id": 4,
      "person_id": 6,
      "committee_member_id": 6,
      "first_name": "Francis",
      "last_name": "Flute",
      "display_name": "Francis Flute",
      "account_email": "replacement@demo.lzug.invalid",
      "person_email": "francis.flute@demo.lzug.invalid",
      "fixture_key": "name.papaspyrou.repertoire.lzug.fixture.person.examiner.replacement"
    }
  },
  "committees": [
    {
      "id": 1,
      "name": "Hauptausschuss Athen",
      "occupation": "Fachinformatiker/in",
      "ihk": "Industrie- und Handelskammer Athen (Demo)",
      "is_active": 1,
      "bootstrap_state": "ready"
    },
    {
      "id": 2,
      "name": "Fremdausschuss Feenwald",
      "occupation": "Fachinformatiker/in",
      "ihk": "Industrie- und Handelskammer Attischer Wald (Demo)",
      "is_active": 1,
      "bootstrap_state": "ready"
    }
  ],
  "members": [
    {
      "id": 1,
      "person_id": 1,
      "committee_id": 1,
      "first_name": "Theseus",
      "last_name": "von Athen",
      "email": "theseus.athen@demo.lzug.invalid",
      "mobile": null,
      "member_status": "ordinary",
      "committee_role": "chair",
      "representing_side": "employer",
      "is_active": 1,
      "email_verified_at": null
    },
    {
      "id": 2,
      "person_id": 2,
      "committee_id": 1,
      "first_name": "Hippolyta",
      "last_name": "von Athen",
      "email": "hippolyta.athen@demo.lzug.invalid",
      "mobile": null,
      "member_status": "ordinary",
      "committee_role": "deputy_chair",
      "representing_side": "school",
      "is_active": 1,
      "email_verified_at": null
    },
    {
      "id": 9,
      "person_id": 9,
      "committee_id": 2,
      "first_name": "Oberon",
      "last_name": "vom Feenwald",
      "email": "oberon.feenwald@demo.lzug.invalid",
      "mobile": null,
      "member_status": "ordinary",
      "committee_role": "chair",
      "representing_side": "employer",
      "is_active": 1,
      "email_verified_at": null
    }
  ],
  "locations": [
    {
      "id": 1,
      "committee_id": null,
      "name": "Prüfungszentrum am Zappeion (Demo)",
      "street": "Vasilissis Olgas Avenue",
      "postal_code": "10557",
      "city": "Athens",
      "room": "Theseussaal",
      "is_active": 1
    },
    {
      "id": 2,
      "committee_id": 1,
      "name": "Prüfungswerkstätten Gazi (Demo)",
      "street": "Pireos 100",
      "postal_code": "11854",
      "city": "Athens",
      "room": "Werkstatt Handwerkerensemble",
      "is_active": 1
    },
    {
      "id": 3,
      "committee_id": 2,
      "name": "Prüfungsbereich Nationalgarten (Demo)",
      "street": "Leoforos Vasilissis Amalias 1",
      "postal_code": "10557",
      "city": "Athens",
      "room": "Lichtung Oberon",
      "is_active": 1
    },
    {
      "id": 4,
      "committee_id": null,
      "name": "Prüfungszentrum am Zappeion (Demo)",
      "street": "Vasilissis Olgas Avenue",
      "postal_code": "10557",
      "city": "Athens",
      "room": "Hippolytasaal",
      "is_active": 1
    },
    {
      "id": 5,
      "committee_id": 1,
      "name": "Prüfungswerkstätten Gazi (Demo)",
      "street": "Pireos 100",
      "postal_code": "11854",
      "city": "Athens",
      "room": "Prüfhalle Pyramus",
      "is_active": 1
    },
    {
      "id": 6,
      "committee_id": 2,
      "name": "Prüfungsbereich Nationalgarten (Demo)",
      "street": "Leoforos Vasilissis Amalias 1",
      "postal_code": "10557",
      "city": "Athens",
      "room": "Lichtung Titania",
      "is_active": 1
    }
  ],
  "examVenues": [
    {
      "id": 1,
      "scope": "global",
      "committee_id": null,
      "name": "Prüfungszentrum am Zappeion (Demo)",
      "street": "Vasilissis Olgas Avenue",
      "postal_code": "10557",
      "city": "Athens",
      "country": "Greece",
      "site_name": "Reale geografische Referenz: Zappeion Megaron, Athen",
      "entrance": "Synthetischer Demo-Eingang und Treffpunkt Theseus",
      "travel_directions": "Reale Orientierung: Bereich Zappeion, fußläufig von Syntagma. Der bezeichnete Eingang und Treffpunkt gehören ausschließlich zum synthetischen Prüfungsszenario.",
      "is_accessible": 1,
      "accessibility_status": "confirmed",
      "accessibility_notes": "Nur im synthetischen Prüfungsszenario als barrierefrei bewertet; keine Aussage über das reale Zappeion.",
      "latitude": 37.97162,
      "longitude": 23.73652,
      "coordinate_status": "confirmed",
      "coordinate_source": "Zappeion-Kontaktseite und OpenStreetMap-Referenz; https://www.zappeion.gr/en/contact.html; Abrufdatum: 2026-09-01",
      "is_active": 1,
      "revision": 1,
      "rooms": [
        {
          "id": 1,
          "venue_id": 1,
          "name": "Theseussaal",
          "building": null,
          "wing": null,
          "floor": null,
          "room_number": null,
          "access_notes": "Synthetische Auffindung: ab Demo-Eingang dem Treffpunkt Theseus folgen.",
          "capacity": 24,
          "is_active": 1,
          "revision": 1,
          "_links": {}
        },
        {
          "id": 4,
          "venue_id": 1,
          "name": "Hippolytasaal",
          "building": null,
          "wing": null,
          "floor": null,
          "room_number": null,
          "access_notes": "Synthetische Auffindung: ab Demo-Eingang dem Hinweis Hippolyta folgen.",
          "capacity": 12,
          "is_active": 1,
          "revision": 1,
          "_links": {}
        }
      ],
      "contacts": [
        {
          "id": 1,
          "venue_id": 1,
          "label": "Hippolyta von Athen",
          "role": "Synthetische Ortskoordination",
          "phone": null,
          "email": "hippolyta.athen@demo.lzug.invalid",
          "availability_notes": "Synthetischer Demo-Kontakt für den gesamten Prüfungsort.",
          "is_active": 1,
          "revision": 1,
          "room_ids": [],
          "_links": {}
        }
      ],
      "map_provider": {
        "mode": "osm",
        "attribution": "© OpenStreetMap-Mitwirkende",
        "attribution_url": "https://www.openstreetmap.org/copyright"
      },
      "capabilities": {
        "manage": false,
        "request_promotion": false,
        "decide_promotion": false
      },
      "_links": {}
    },
    {
      "id": 2,
      "scope": "committee",
      "committee_id": 1,
      "name": "Prüfungswerkstätten Gazi (Demo)",
      "street": "Pireos 100",
      "postal_code": "11854",
      "city": "Athens",
      "country": "Greece",
      "site_name": "Reale geografische Referenz: Technopolis City of Athens",
      "entrance": "Synthetisches Demo-Tor und Treffpunkt Handwerkerensemble",
      "travel_directions": "Reale Orientierung: Metrostation Kerameikos und Pireos 100. Das bezeichnete Tor und der Treffpunkt gehören ausschließlich zum synthetischen Prüfungsszenario.",
      "is_accessible": 1,
      "accessibility_status": "confirmed",
      "accessibility_notes": "Nur im synthetischen Prüfungsszenario als barrierefrei bewertet; keine Aussage über die reale Technopolis.",
      "latitude": 37.977779,
      "longitude": 23.714099,
      "coordinate_status": "confirmed",
      "coordinate_source": "Technopolis City of Athens; https://www.athens-technopolis.gr/index.php/en/contact-us-eng; Abrufdatum: 2026-09-01",
      "is_active": 1,
      "revision": 1,
      "rooms": [
        {
          "id": 2,
          "venue_id": 2,
          "name": "Werkstatt Handwerkerensemble",
          "building": null,
          "wing": null,
          "floor": null,
          "room_number": null,
          "access_notes": "Synthetische Auffindung: ab Demo-Tor dem Treffpunkt Handwerkerensemble folgen.",
          "capacity": 18,
          "is_active": 1,
          "revision": 1,
          "_links": {}
        },
        {
          "id": 5,
          "venue_id": 2,
          "name": "Prüfhalle Pyramus",
          "building": null,
          "wing": null,
          "floor": null,
          "room_number": null,
          "access_notes": "Synthetische Auffindung: ab Demo-Tor dem Hinweis Pyramus folgen.",
          "capacity": 30,
          "is_active": 1,
          "revision": 1,
          "_links": {}
        }
      ],
      "contacts": [
        {
          "id": 2,
          "venue_id": 2,
          "label": "Peter Quince",
          "role": "Synthetische Raumkoordination",
          "phone": null,
          "email": "peter.quince@demo.lzug.invalid",
          "availability_notes": "Synthetischer Demo-Kontakt ausschließlich für die Werkstatt Handwerkerensemble.",
          "is_active": 1,
          "revision": 1,
          "room_ids": [
            2
          ],
          "_links": {}
        }
      ],
      "map_provider": {
        "mode": "osm",
        "attribution": "© OpenStreetMap-Mitwirkende",
        "attribution_url": "https://www.openstreetmap.org/copyright"
      },
      "capabilities": {
        "manage": false,
        "request_promotion": false,
        "decide_promotion": false
      },
      "_links": {}
    },
    {
      "id": 3,
      "scope": "committee",
      "committee_id": 2,
      "name": "Prüfungsbereich Nationalgarten (Demo)",
      "street": "Leoforos Vasilissis Amalias 1",
      "postal_code": "10557",
      "city": "Athens",
      "country": "Greece",
      "site_name": "Reale geografische Referenz: National Garden of Athens",
      "entrance": "Synthetischer Treffpunkt Feenwald",
      "travel_directions": "Reale Orientierung: Haupteingang an der Amalias-Allee und Umgebung Syntagma. Der bezeichnete Treffpunkt gehört ausschließlich zum synthetischen Prüfungsszenario.",
      "is_accessible": 0,
      "accessibility_status": "confirmed",
      "accessibility_notes": "Der für das Demo-Szenario angenommene Außenbereich besitzt unebene Wege und wird nicht als barrierefrei bewertet. Dies ist keine Aussage über den realen Nationalgarten.",
      "latitude": 37.973365,
      "longitude": 23.73769,
      "coordinate_status": "confirmed",
      "coordinate_source": "Stadt Athen, Nationalgarten; https://old.cityofathens.gr/episkeptes/aksiotheata/diadromes-stin-istoria-tis-athinas/o-kipos-tis-athinas; Abrufdatum: 2026-09-01",
      "is_active": 1,
      "revision": 1,
      "rooms": [
        {
          "id": 3,
          "venue_id": 3,
          "name": "Lichtung Oberon",
          "building": null,
          "wing": null,
          "floor": null,
          "room_number": null,
          "access_notes": "Synthetische Auffindung: ab Treffpunkt Feenwald der Demo-Beschilderung Oberon folgen.",
          "capacity": 15,
          "is_active": 1,
          "revision": 1,
          "_links": {}
        },
        {
          "id": 6,
          "venue_id": 3,
          "name": "Lichtung Titania",
          "building": null,
          "wing": null,
          "floor": null,
          "room_number": null,
          "access_notes": "Synthetische Auffindung: ab Treffpunkt Feenwald der Demo-Beschilderung Titania folgen.",
          "capacity": 15,
          "is_active": 1,
          "revision": 1,
          "_links": {}
        }
      ],
      "contacts": [],
      "map_provider": {
        "mode": "osm",
        "attribution": "© OpenStreetMap-Mitwirkende",
        "attribution_url": "https://www.openstreetmap.org/copyright"
      },
      "capabilities": {
        "manage": false,
        "request_promotion": false,
        "decide_promotion": false
      },
      "_links": {}
    }
  ],
  "candidates": [
    {
      "id": 1,
      "first_name": "Hermia",
      "last_name": "von Athen",
      "ihk_exam_number": "ATHEN-DEMO-2026-0001",
      "specialization": "Anwendungsentwicklung",
      "training_company": "Atelier Athen (Demo)"
    },
    {
      "id": 2,
      "first_name": "Helena",
      "last_name": "von Athen",
      "ihk_exam_number": "ATHEN-DEMO-2026-0002",
      "specialization": "Systemintegration",
      "training_company": "Werkstatt Athen (Demo)"
    }
  ]
} as const;
