// Generated by scripts/generate_synthetic_fixtures.py. Do not edit directly.
export const syntheticFixtures = {
  "committees": [
    {
      "id": 1,
      "name": "Prüfungsausschuss Teststadt 1",
      "ihk": "IHK Teststadt",
      "occupation": "Fachinformatiker/in"
    },
    {
      "id": 2,
      "name": "Prüfungsausschuss Teststadt 2",
      "ihk": "IHK Teststadt",
      "occupation": "Fachinformatiker/in"
    }
  ],
  "members": [
    {
      "id": 1,
      "person_id": 1,
      "committee_id": 1,
      "first_name": "Testperson",
      "last_name": "Alpha",
      "email": "testperson.alpha@example.invalid",
      "mobile": "+49 000 0000001",
      "member_status": "ordinary",
      "committee_role": "chair",
      "representing_side": "employer",
      "is_active": 1,
      "email_verified_at": null
    },
    {
      "id": 2,
      "person_id": 2,
      "committee_id": 1,
      "first_name": "Testperson",
      "last_name": "Beta",
      "email": "testperson.beta@example.invalid",
      "mobile": "+49 000 0000002",
      "member_status": "ordinary",
      "committee_role": "member",
      "representing_side": "school",
      "is_active": 0,
      "email_verified_at": null
    },
    {
      "id": 9,
      "person_id": 9,
      "committee_id": 2,
      "first_name": "Testperson",
      "last_name": "Iota",
      "email": "testperson.iota@example.invalid",
      "mobile": null,
      "member_status": "deputy",
      "committee_role": "member",
      "representing_side": "employee",
      "is_active": 1,
      "email_verified_at": null
    }
  ],
  "locations": [
    {
      "id": 1,
      "committee_id": 1,
      "name": "Prüfungszentrum Alpha (Test)",
      "street": "Testweg 1",
      "postal_code": "00000",
      "city": "Teststadt",
      "room": "Testraum A-01",
      "is_active": 1
    }
  ],
  "candidates": [
    {
      "id": 1,
      "first_name": "Prüfling",
      "last_name": "Alpha",
      "ihk_exam_number": "TEST-2026-0001",
      "specialization": "Anwendungsentwicklung",
      "training_company": "Testbetrieb Alpha"
    },
    {
      "id": 2,
      "first_name": "Prüfling",
      "last_name": "Beta",
      "ihk_exam_number": "TEST-2026-0002",
      "specialization": "Systemintegration",
      "training_company": "Testbetrieb Beta"
    }
  ]
} as const;
