// Generated by scripts/generate_synthetic_fixtures.py. Do not edit directly.
export const syntheticFixtures = {
  "version": 2,
  "revision": "midsummer-night-dream-v2",
  "fixtureRoot": "name.papaspyrou.repertoire.lzug.fixture",
  "demoMatrixVersion": "demo-paths-v7",
  "keys": {
    "committees": {
      "name.papaspyrou.repertoire.lzug.fixture.committee.athen": 1,
      "name.papaspyrou.repertoire.lzug.fixture.committee.feenwald": 2
    },
    "persons": {
      "name.papaspyrou.repertoire.lzug.fixture.person.chair.athen": 1,
      "name.papaspyrou.repertoire.lzug.fixture.person.deputy.athen": 2,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.absent": 3,
      "name.papaspyrou.repertoire.lzug.fixture.person.crosscommittee": 4,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.fallback": 5,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.replacement": 6,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.unsuitable": 7,
      "name.papaspyrou.repertoire.lzug.fixture.person.examiner.reserve": 8,
      "name.papaspyrou.repertoire.lzug.fixture.person.chair.feenwald": 9,
      "name.papaspyrou.repertoire.lzug.fixture.person.deputy.feenwald": 10
    },
    "memberships": {
      "name.papaspyrou.repertoire.lzug.fixture.membership.chair.athen": 1,
      "name.papaspyrou.repertoire.lzug.fixture.membership.deputy.athen": 2,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.absent": 3,
      "name.papaspyrou.repertoire.lzug.fixture.membership.crosscommittee.athen": 4,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.fallback": 5,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.replacement": 6,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.unsuitable": 7,
      "name.papaspyrou.repertoire.lzug.fixture.membership.examiner.reserve": 8,
      "name.papaspyrou.repertoire.lzug.fixture.membership.chair.feenwald": 9,
      "name.papaspyrou.repertoire.lzug.fixture.membership.deputy.feenwald": 10,
      "name.papaspyrou.repertoire.lzug.fixture.membership.crosscommittee.feenwald": 11
    },
    "accounts": {
      "name.papaspyrou.repertoire.lzug.fixture.account.chair": 1,
      "name.papaspyrou.repertoire.lzug.fixture.account.examiner": 2,
      "name.papaspyrou.repertoire.lzug.fixture.account.deputy": 3,
      "name.papaspyrou.repertoire.lzug.fixture.account.replacement": 4
    },
    "locations": {
      "name.papaspyrou.repertoire.lzug.fixture.location.synthetic.court": 1,
      "name.papaspyrou.repertoire.lzug.fixture.location.synthetic.garden": 2,
      "name.papaspyrou.repertoire.lzug.fixture.location.synthetic.feenwald": 3
    },
    "candidates": {
      "name.papaspyrou.repertoire.lzug.fixture.candidate.planchange": 1,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.absence": 2,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.lysander": 3,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.demetrius": 4,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.egeus": 5,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.philostrate": 6,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.peaseblossom": 7,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.cobweb": 8,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.moth": 9,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.mustardseed": 10,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.moonshine": 11,
      "name.papaspyrou.repertoire.lzug.fixture.candidate.lion": 12
    }
  },
  "demoRoles": {
    "chair": {
      "account_id": 1,
      "person_id": 1,
      "committee_member_id": 1,
      "first_name": "Theseus",
      "last_name": "von Athen",
      "display_name": "Theseus von Athen",
      "account_email": "chair@demo.lzug.invalid",
      "person_email": "theseus.athen@demo.lzug.invalid",
      "fixture_key": "name.papaspyrou.repertoire.lzug.fixture.person.chair.athen"
    },
    "examiner": {
      "account_id": 2,
      "person_id": 3,
      "committee_member_id": 3,
      "first_name": "Peter",
      "last_name": "Quince",
      "display_name": "Peter Quince",
      "account_email": "examiner@demo.lzug.invalid",
      "person_email": "peter.quince@demo.lzug.invalid",
      "fixture_key": "name.papaspyrou.repertoire.lzug.fixture.person.examiner.absent"
    },
    "replacement": {
      "account_id": 4,
      "person_id": 6,
      "committee_member_id": 6,
      "first_name": "Francis",
      "last_name": "Flute",
      "display_name": "Francis Flute",
      "account_email": "replacement@demo.lzug.invalid",
      "person_email": "francis.flute@demo.lzug.invalid",
      "fixture_key": "name.papaspyrou.repertoire.lzug.fixture.person.examiner.replacement"
    }
  },
  "committees": [
    {
      "id": 1,
      "name": "Hauptausschuss Athen",
      "occupation": "Fachinformatiker/in",
      "ihk": "Industrie- und Handelskammer Athen (Demo)",
      "is_active": 1,
      "bootstrap_state": "ready"
    },
    {
      "id": 2,
      "name": "Fremdausschuss Feenwald",
      "occupation": "Fachinformatiker/in",
      "ihk": "Industrie- und Handelskammer Attischer Wald (Demo)",
      "is_active": 1,
      "bootstrap_state": "ready"
    }
  ],
  "members": [
    {
      "id": 1,
      "person_id": 1,
      "committee_id": 1,
      "first_name": "Theseus",
      "last_name": "von Athen",
      "email": "theseus.athen@demo.lzug.invalid",
      "mobile": null,
      "member_status": "ordinary",
      "committee_role": "chair",
      "representing_side": "employer",
      "is_active": 1,
      "email_verified_at": null
    },
    {
      "id": 2,
      "person_id": 2,
      "committee_id": 1,
      "first_name": "Hippolyta",
      "last_name": "von Athen",
      "email": "hippolyta.athen@demo.lzug.invalid",
      "mobile": null,
      "member_status": "ordinary",
      "committee_role": "deputy_chair",
      "representing_side": "school",
      "is_active": 1,
      "email_verified_at": null
    },
    {
      "id": 9,
      "person_id": 9,
      "committee_id": 2,
      "first_name": "Oberon",
      "last_name": "vom Feenwald",
      "email": "oberon.feenwald@demo.lzug.invalid",
      "mobile": null,
      "member_status": "ordinary",
      "committee_role": "chair",
      "representing_side": "employer",
      "is_active": 1,
      "email_verified_at": null
    }
  ],
  "locations": [
    {
      "id": 1,
      "committee_id": 1,
      "name": "Hof Athen (synthetisch)",
      "street": "Demoallee 1",
      "postal_code": "00000",
      "city": "Athen (Demo)",
      "room": "Saal Theseus",
      "is_active": 1
    },
    {
      "id": 3,
      "committee_id": 2,
      "name": "Lichtung Feenwald (synthetisch)",
      "street": "Fiktiver Waldpfad 1",
      "postal_code": "00000",
      "city": "Attischer Wald (Demo)",
      "room": "Lichtung Oberon",
      "is_active": 1
    }
  ],
  "candidates": [
    {
      "id": 1,
      "first_name": "Hermia",
      "last_name": "von Athen",
      "ihk_exam_number": "ATHEN-DEMO-2026-0001",
      "specialization": "Anwendungsentwicklung",
      "training_company": "Atelier Athen (Demo)"
    },
    {
      "id": 2,
      "first_name": "Helena",
      "last_name": "von Athen",
      "ihk_exam_number": "ATHEN-DEMO-2026-0002",
      "specialization": "Systemintegration",
      "training_company": "Werkstatt Athen (Demo)"
    }
  ]
} as const;
