package admincli

import (
	"fmt"
	"sort"
	"strings"
)

func GenerateCompletion(registry *Registry, shell string) (string, error) {
	switch shell {
	case "bash":
		return bashCompletion(registry), nil
	case "zsh":
		return zshCompletion(registry), nil
	case "fish":
		return fishCompletion(registry), nil
	case "powershell":
		return powershellCompletion(registry), nil
	default:
		return "", fmt.Errorf("unsupported completion shell %q", shell)
	}
}

func rootTokens(registry *Registry) []string {
	tokens := []string{}
	for _, group := range registry.Groups() {
		tokens = append(tokens, group.Name)
	}
	for _, command := range registry.Commands() {
		if len(command.Path) == 1 {
			tokens = append(tokens, command.Path[0])
		}
	}
	sort.Strings(tokens)
	return compact(tokens)
}

func globalOptionTokens() []string {
	tokens := []string{"--build-metadata", "--help", "--version"}
	for _, option := range GlobalOptionSpecs() {
		tokens = append(tokens, "--"+option.Name)
	}
	sort.Strings(tokens)
	return tokens
}

func actionTokens(registry *Registry, group string) []string {
	actions := []string{}
	for _, command := range registry.CommandsInGroup(group) {
		actions = append(actions, command.Path[1])
	}
	return actions
}

func commandOptionTokens(command *Command) []string {
	options := []string{"--help"}
	for _, option := range GlobalOptionSpecs() {
		if option.Name == "force" && !command.Confirmation.Required {
			continue
		}
		options = append(options, "--"+option.Name)
	}
	for _, option := range command.Options {
		options = append(options, "--"+option.Name)
	}
	sort.Strings(options)
	return compact(options)
}

func bashCompletion(registry *Registry) string {
	var output strings.Builder
	output.WriteString("# Generated by lzug-admin from its static command registry.\n")
	output.WriteString("_lzug_admin_completion() {\n")
	output.WriteString("  local cur root action candidates word\n")
	output.WriteString("  local -i index\n")
	output.WriteString("  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	output.WriteString("  root=\"\"\n")
	output.WriteString("  action=\"\"\n")
	output.WriteString("  index=1\n")
	output.WriteString("  while (( index < COMP_CWORD )); do\n")
	output.WriteString("    word=\"${COMP_WORDS[index]}\"\n")
	output.WriteString("    case \"$word\" in\n")
	output.WriteString("      --engine|--container|--config) ((index += 2)); continue ;;\n")
	output.WriteString("      --engine=*|--container=*|--config=*|--no-config|--json|--verbose|--force|--help|--version|--build-metadata) ((index++)); continue ;;\n")
	output.WriteString("      --*) ((index++)); continue ;;\n")
	output.WriteString("    esac\n")
	output.WriteString("    if [[ -z $root ]]; then root=\"$word\"; elif [[ -z $action ]]; then action=\"$word\"; fi\n")
	output.WriteString("    ((index++))\n")
	output.WriteString("  done\n")
	fmt.Fprintf(&output, "  candidates=\"%s\"\n", strings.Join(globalOptionTokens(), " "))
	output.WriteString("  if [[ -z $root ]]; then\n")
	fmt.Fprintf(&output, "    candidates=\"$candidates %s\"\n", strings.Join(rootTokens(registry), " "))
	output.WriteString("  elif [[ -z $action ]]; then\n")
	output.WriteString("    case \"$root\" in\n")
	for _, group := range registry.Groups() {
		fmt.Fprintf(&output, "      %s) candidates=\"$candidates %s\" ;;\n", group.Name, strings.Join(actionTokens(registry, group.Name), " "))
	}
	output.WriteString("    esac\n")
	output.WriteString("  else\n")
	output.WriteString("    case \"$root $action\" in\n")
	for _, command := range registry.Commands() {
		if len(command.Path) == 1 {
			fmt.Fprintf(&output, "      \"%s \" ) candidates=\"%s\" ;;\n", command.Name(), strings.Join(commandOptionTokens(command), " "))
		} else {
			fmt.Fprintf(&output, "      \"%s\") candidates=\"%s\" ;;\n", command.Name(), strings.Join(commandOptionTokens(command), " "))
		}
	}
	output.WriteString("    esac\n")
	output.WriteString("  fi\n")
	output.WriteString("  COMPREPLY=( $(compgen -W \"$candidates\" -- \"$cur\") )\n")
	output.WriteString("}\n")
	output.WriteString("complete -F _lzug_admin_completion lzug-admin\n")
	return output.String()
}

func zshCompletion(registry *Registry) string {
	var output strings.Builder
	output.WriteString("#compdef lzug-admin\n")
	output.WriteString("# Generated by lzug-admin from its static command registry.\n")
	output.WriteString("_lzug_admin() {\n")
	output.WriteString("  local -a candidates\n")
	output.WriteString("  local root action word\n")
	output.WriteString("  integer index\n")
	output.WriteString("  root=''\n")
	output.WriteString("  action=''\n")
	output.WriteString("  index=2\n")
	output.WriteString("  while (( index < CURRENT )); do\n")
	output.WriteString("    word=$words[index]\n")
	output.WriteString("    case $word in\n")
	output.WriteString("      --engine|--container|--config) (( index += 2 )); continue ;;\n")
	output.WriteString("      --engine=*|--container=*|--config=*|--no-config|--json|--verbose|--force|--help|--version|--build-metadata) (( index++ )); continue ;;\n")
	output.WriteString("      --*) (( index++ )); continue ;;\n")
	output.WriteString("    esac\n")
	output.WriteString("    if [[ -z $root ]]; then root=$word; elif [[ -z $action ]]; then action=$word; fi\n")
	output.WriteString("    (( index++ ))\n")
	output.WriteString("  done\n")
	output.WriteString("  if [[ -z $root ]]; then\n")
	fmt.Fprintf(&output, "    candidates=(%s %s)\n", strings.Join(rootTokens(registry), " "), strings.Join(globalOptionTokens(), " "))
	output.WriteString("  elif [[ -z $action ]]; then\n")
	output.WriteString("    candidates=(")
	output.WriteString(strings.Join(globalOptionTokens(), " "))
	output.WriteString(")\n")
	output.WriteString("    case $root in\n")
	for _, group := range registry.Groups() {
		fmt.Fprintf(&output, "      %s) candidates=(%s %s) ;;\n", group.Name, strings.Join(actionTokens(registry, group.Name), " "), strings.Join(globalOptionTokens(), " "))
	}
	output.WriteString("    esac\n")
	output.WriteString("  else\n")
	output.WriteString("    case \"$root $action\" in\n")
	for _, command := range registry.Commands() {
		if len(command.Path) != 2 {
			continue
		}
		fmt.Fprintf(&output, "      \"%s\") candidates=(%s) ;;\n", command.Name(), strings.Join(commandOptionTokens(command), " "))
	}
	output.WriteString("      *) candidates=(")
	output.WriteString(strings.Join(globalOptionTokens(), " "))
	output.WriteString(") ;;\n")
	output.WriteString("    esac\n")
	output.WriteString("  fi\n")
	output.WriteString("  compadd -- $candidates\n")
	output.WriteString("}\n")
	output.WriteString("compdef _lzug_admin lzug-admin\n")
	return output.String()
}

func fishCompletion(registry *Registry) string {
	var output strings.Builder
	output.WriteString("# Generated by lzug-admin from its static command registry.\n")
	output.WriteString("function __lzug_admin_path\n")
	output.WriteString("    set -l words (commandline -opc)\n")
	output.WriteString("    set -e words[1]\n")
	output.WriteString("    set -l path\n")
	output.WriteString("    set -l skip_value 0\n")
	output.WriteString("    for word in $words\n")
	output.WriteString("        if test $skip_value -eq 1\n")
	output.WriteString("            set skip_value 0\n")
	output.WriteString("            continue\n")
	output.WriteString("        end\n")
	output.WriteString("        switch $word\n")
	output.WriteString("            case --engine --container --config\n")
	output.WriteString("                set skip_value 1\n")
	output.WriteString("                continue\n")
	output.WriteString("            case '--engine=*' '--container=*' '--config=*' --no-config --json --verbose --force --help --version --build-metadata\n")
	output.WriteString("                continue\n")
	output.WriteString("            case '--*'\n")
	output.WriteString("                continue\n")
	output.WriteString("            case '*'\n")
	output.WriteString("                set -a path $word\n")
	output.WriteString("        end\n")
	output.WriteString("        if test (count $path) -eq 2\n")
	output.WriteString("            break\n")
	output.WriteString("        end\n")
	output.WriteString("    end\n")
	output.WriteString("    if test (count $path) -eq 0\n")
	output.WriteString("        echo root\n")
	output.WriteString("    else if test (count $path) -eq 1\n")
	output.WriteString("        echo root:$path[1]\n")
	output.WriteString("    else\n")
	output.WriteString("        echo command:$path[1]:$path[2]\n")
	output.WriteString("    end\n")
	output.WriteString("end\n")
	output.WriteString("function __lzug_admin_at\n")
	output.WriteString("    test (__lzug_admin_path) = $argv[1]\n")
	output.WriteString("end\n")
	output.WriteString("complete -c lzug-admin -f\n")
	for _, option := range GlobalOptionSpecs() {
		if option.Name == "force" {
			continue
		}
		fmt.Fprintf(&output, "complete -c lzug-admin -l %s\n", option.Name)
	}
	output.WriteString("complete -c lzug-admin -l help\n")
	output.WriteString("complete -c lzug-admin -l version\n")
	output.WriteString("complete -c lzug-admin -l build-metadata\n")
	roots := rootTokens(registry)
	for _, root := range roots {
		fmt.Fprintf(&output, "complete -c lzug-admin -n '__lzug_admin_at root' -a %s\n", root)
	}
	for _, group := range registry.Groups() {
		actions := actionTokens(registry, group.Name)
		for _, action := range actions {
			fmt.Fprintf(&output, "complete -c lzug-admin -n '__lzug_admin_at root:%s' -a %s\n", group.Name, action)
		}
	}
	for _, command := range registry.Commands() {
		if len(command.Path) != 2 {
			continue
		}
		if command.Confirmation.Required {
			fmt.Fprintf(&output, "complete -c lzug-admin -n '__lzug_admin_at command:%s:%s' -l force\n", command.Path[0], command.Path[1])
		}
		for _, option := range command.Options {
			fmt.Fprintf(&output, "complete -c lzug-admin -n '__lzug_admin_at command:%s:%s' -l %s\n", command.Path[0], command.Path[1], option.Name)
		}
	}
	return output.String()
}

func powershellCompletion(registry *Registry) string {
	var output strings.Builder
	output.WriteString("# Generated by lzug-admin from its static command registry.\n")
	output.WriteString("Register-ArgumentCompleter -Native -CommandName lzug-admin -ScriptBlock {\n")
	output.WriteString("  param($wordToComplete, $commandAst, $cursorPosition)\n")
	output.WriteString("  $globalCandidates = @(")
	output.WriteString(quotedPowerShell(globalOptionTokens()))
	output.WriteString(")\n")
	output.WriteString("  $rootCandidates = @(")
	output.WriteString(quotedPowerShell(rootTokens(registry)))
	output.WriteString(")\n")
	output.WriteString("  $actions = @{\n")
	for _, group := range registry.Groups() {
		fmt.Fprintf(&output, "    '%s' = @(%s)\n", group.Name, quotedPowerShell(actionTokens(registry, group.Name)))
	}
	output.WriteString("  }\n")
	output.WriteString("  $options = @{\n")
	for _, command := range registry.Commands() {
		fmt.Fprintf(&output, "    '%s' = @(%s)\n", command.Name(), quotedPowerShell(commandOptionTokens(command)))
	}
	output.WriteString("  }\n")
	output.WriteString("  $completed = @($commandAst.CommandElements | Where-Object { $_.Extent.EndOffset -lt $cursorPosition } | Select-Object -Skip 1 | ForEach-Object { $_.Extent.Text })\n")
	output.WriteString("  $path = @()\n")
	output.WriteString("  $skipValue = $false\n")
	output.WriteString("  foreach ($entry in $completed) {\n")
	output.WriteString("    if ($skipValue) { $skipValue = $false; continue }\n")
	output.WriteString("    if (@('--engine', '--container', '--config') -contains $entry) { $skipValue = $true; continue }\n")
	output.WriteString("    if ($entry -match '^--(engine|container|config)=' -or $entry.StartsWith('--')) { continue }\n")
	output.WriteString("    if ($path.Count -lt 2) { $path += $entry }\n")
	output.WriteString("  }\n")
	output.WriteString("  $candidates = @($globalCandidates)\n")
	output.WriteString("  if ($path.Count -eq 0) {\n")
	output.WriteString("    $candidates += $rootCandidates\n")
	output.WriteString("  } elseif ($path.Count -eq 1 -and $actions.ContainsKey($path[0])) {\n")
	output.WriteString("    $candidates += $actions[$path[0]]\n")
	output.WriteString("  } else {\n")
	output.WriteString("    $key = ($path -join ' ')\n")
	output.WriteString("    if ($options.ContainsKey($key)) { $candidates += $options[$key] }\n")
	output.WriteString("  }\n")
	output.WriteString("  $candidates | Sort-Object -Unique | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {\n")
	output.WriteString("    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)\n")
	output.WriteString("  }\n")
	output.WriteString("}\n")
	return output.String()
}

func quotedPowerShell(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = "'" + strings.ReplaceAll(value, "'", "''") + "'"
	}
	return strings.Join(quoted, ", ")
}
