package admincli

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestHelpMatchesRegistryGoldenFiles(t *testing.T) {
	registry, err := DefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	for _, test := range []struct {
		name   string
		target string
	}{
		{name: "help-root.golden", target: "root"},
		{name: "help-account.golden", target: "account"},
		{name: "help-backup-restore.golden", target: "backup restore"},
	} {
		actual, found := Help(registry, test.target)
		if !found {
			t.Fatalf("help target %q was not found", test.target)
		}
		assertGolden(t, test.name, actual)
	}
}

func TestCompletionIsStaticCompleteAndSecretFree(t *testing.T) {
	registry, err := DefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	for _, shell := range []string{"bash", "zsh", "fish", "powershell"} {
		script, generateErr := GenerateCompletion(registry, shell)
		if generateErr != nil {
			t.Fatal(generateErr)
		}
		for _, required := range []string{"account", "committee", "backup", "export", "completion", "container", "json"} {
			if !strings.Contains(script, required) {
				t.Fatalf("%s completion lacks %q", shell, required)
			}
		}
		for _, forbidden := range []string{"example.invalid", "PRIVATE_KEY", "one-time", "recipient-private-key", "token"} {
			if strings.Contains(script, forbidden) {
				t.Fatalf("%s completion contains sensitive or dynamic value %q", shell, forbidden)
			}
		}
		if strings.Count(script, "Generated by lzug-admin") != 1 {
			t.Fatalf("%s completion does not have one generated marker", shell)
		}
	}
}

func TestBashCompletionIsSyntacticallyValid(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash is unavailable")
	}
	registry, err := DefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	script, err := GenerateCompletion(registry, "bash")
	if err != nil {
		t.Fatal(err)
	}
	command := exec.Command("bash", "-n")
	command.Stdin = strings.NewReader(script)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("bash completion is invalid: %v: %s", err, output)
	}
}

func TestBashCompletionFindsCommandAfterGlobalOptionValues(t *testing.T) {
	path, err := exec.LookPath("bash")
	if err != nil {
		t.Skip("bash is unavailable")
	}
	registry, err := DefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	script, err := GenerateCompletion(registry, "bash")
	if err != nil {
		t.Fatal(err)
	}
	script += "\nCOMP_WORDS=(lzug-admin --container lzug account invite --e)\n"
	script += "COMP_CWORD=5\n_lzug_admin_completion\nprintf '%s\\n' \"${COMPREPLY[@]}\"\n"
	output, err := exec.Command(path, "-c", script).CombinedOutput()
	if err != nil {
		t.Fatalf("bash completion failed: %v: %s", err, output)
	}
	completed := string(output)
	if !strings.Contains(completed, "--email\n") || strings.Contains(completed, "account\n") || strings.Contains(completed, "--artifact\n") {
		t.Fatalf("contextual completion did not survive global option values: %q", output)
	}
}

func TestAvailableShellsAcceptGeneratedCompletionSyntax(t *testing.T) {
	registry, err := DefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		shell      string
		executable string
		arguments  []string
		extension  string
	}{
		{shell: "zsh", executable: "zsh", arguments: []string{"-n"}, extension: ".zsh"},
		{shell: "fish", executable: "fish", arguments: []string{"--no-execute"}, extension: ".fish"},
		{shell: "powershell", executable: "pwsh", arguments: []string{"-NoProfile", "-NonInteractive", "-File"}, extension: ".ps1"},
	}
	for _, test := range tests {
		t.Run(test.shell, func(t *testing.T) {
			path, lookupErr := exec.LookPath(test.executable)
			if lookupErr != nil {
				t.Skipf("%s is unavailable", test.executable)
			}
			script, generateErr := GenerateCompletion(registry, test.shell)
			if generateErr != nil {
				t.Fatal(generateErr)
			}
			file := filepath.Join(t.TempDir(), "completion"+test.extension)
			if writeErr := os.WriteFile(file, []byte(script), 0o600); writeErr != nil {
				t.Fatal(writeErr)
			}
			arguments := append(append([]string{}, test.arguments...), file)
			if output, runErr := exec.Command(path, arguments...).CombinedOutput(); runErr != nil {
				t.Fatalf("%s completion is invalid: %v: %s", test.shell, runErr, output)
			}
		})
	}
}

func TestGeneratedCompletionKeepsContextAndScopesForce(t *testing.T) {
	registry, err := DefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	zsh, err := GenerateCompletion(registry, "zsh")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(zsh, `case "$root $action" in`) || strings.Contains(zsh, `case "$words[2] $words[3]" in`) {
		t.Fatal("zsh completion does not use the parsed command context")
	}
	fish, err := GenerateCompletion(registry, "fish")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(fish, "complete -c lzug-admin -l force\n") {
		t.Fatal("fish completion offers --force without a destructive command context")
	}
	if !strings.Contains(fish, "-n '__lzug_admin_at command:account:disable' -l force\n") ||
		strings.Contains(fish, "-n '__lzug_admin_at command:account:invite' -l force\n") {
		t.Fatal("fish completion does not scope --force to destructive commands")
	}
}

func TestGeneratedReferenceContainsEveryCommandAndMigration(t *testing.T) {
	registry, err := DefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	reference := GenerateReference(registry)
	for _, command := range registry.Commands() {
		if !strings.Contains(reference, "### `lzug-admin "+command.Name()+"`") {
			t.Fatalf("reference lacks command %q", command.Name())
		}
		for _, old := range command.LegacyForms {
			if !strings.Contains(reference, "`lzug-admin "+old+"`") {
				t.Fatalf("reference lacks legacy form %q", old)
			}
		}
	}
	if strings.Count(reference, "<!-- Generated from operator-cli/internal/admincli registry metadata.") != 1 {
		t.Fatal("reference lacks generated marker")
	}
}

func TestCheckedInReferenceAndReleaseMigrationMatchRegistry(t *testing.T) {
	registry, err := DefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	_, source, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("test source path is unavailable")
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(source), "..", "..", ".."))
	reference, err := os.ReadFile(filepath.Join(root, "docs", "developers", "reference", "cli.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(reference, []byte(GenerateReference(registry))) {
		t.Fatal("checked-in CLI reference is stale")
	}
	changelog, err := os.ReadFile(filepath.Join(root, "CHANGELOG.md"))
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(string(changelog), "\n")
	for _, command := range registry.Commands() {
		for _, legacy := range command.LegacyForms {
			legacy = strings.Split(legacy, " (")[0]
			found := false
			for _, line := range lines {
				if strings.Contains(line, "`lzug-admin "+legacy+"`") && strings.Contains(line, "`lzug-admin "+command.Name()+"`") {
					found = true
					break
				}
			}
			if !found {
				t.Fatalf("CHANGELOG lacks migration from %q to %q", legacy, command.Name())
			}
		}
	}
}

func assertGolden(t *testing.T, name, actual string) {
	t.Helper()
	path := filepath.Join("testdata", name)
	expected, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(expected, []byte(actual)) {
		t.Fatalf("%s does not match registry output", name)
	}
}
