-- Generated by scripts/generate_synthetic_fixtures.py. Do not edit directly.
INSERT INTO committee (id, name, occupation, ihk, is_active, bootstrap_state)
VALUES
  (1, 'Hauptausschuss Athen', 'Fachinformatiker/in', 'Industrie- und Handelskammer Athen (Demo)', 1, 'ready'),
  (2, 'Fremdausschuss Feenwald', 'Fachinformatiker/in', 'Industrie- und Handelskammer Attischer Wald (Demo)', 1, 'ready');

INSERT INTO person (id, first_name, last_name, email, mobile)
VALUES
  (1, 'Theseus', 'von Athen', 'theseus.athen@demo.lzug.invalid', NULL),
  (2, 'Hippolyta', 'von Athen', 'hippolyta.athen@demo.lzug.invalid', NULL),
  (3, 'Peter', 'Quince', 'peter.quince@demo.lzug.invalid', NULL),
  (4, 'Robin', 'Goodfellow', 'robin.goodfellow@demo.lzug.invalid', NULL),
  (5, 'Nick', 'Bottom', 'nick.bottom@demo.lzug.invalid', NULL),
  (6, 'Francis', 'Flute', 'francis.flute@demo.lzug.invalid', NULL),
  (7, 'Tom', 'Snout', 'tom.snout@demo.lzug.invalid', NULL),
  (8, 'Snug', 'vom Ensemble', 'snug.ensemble@demo.lzug.invalid', NULL),
  (9, 'Oberon', 'vom Feenwald', 'oberon.feenwald@demo.lzug.invalid', NULL),
  (10, 'Titania', 'vom Feenwald', 'titania.feenwald@demo.lzug.invalid', NULL);

INSERT INTO committee_member
  (id, person_id, committee_id, member_status, committee_role, representing_side)
VALUES
  (1, 1, 1, 'ordinary', 'chair', 'employer'),
  (2, 2, 1, 'ordinary', 'deputy_chair', 'school'),
  (3, 3, 1, 'ordinary', 'member', 'employee'),
  (4, 4, 1, 'ordinary', 'member', 'employer'),
  (5, 5, 1, 'deputy', 'member', 'school'),
  (6, 6, 1, 'deputy', 'member', 'employee'),
  (7, 7, 1, 'deputy', 'member', 'employer'),
  (8, 8, 1, 'deputy', 'member', 'school'),
  (9, 9, 2, 'ordinary', 'chair', 'employer'),
  (10, 10, 2, 'ordinary', 'deputy_chair', 'employee'),
  (11, 4, 2, 'deputy', 'member', 'school');

INSERT INTO user_account (id, person_id, email, password_hash)
VALUES
  (1, 1, 'chair@demo.lzug.invalid', 'demo-password-hash'),
  (2, 3, 'examiner@demo.lzug.invalid', 'demo-password-hash'),
  (3, 2, 'deputy@demo.lzug.invalid', 'demo-password-hash');

INSERT INTO committee_admin_operation (
  operation_type, committee_id, person_ids_json, membership_ids_json,
  account_ids_json, result, occurred_at, technical_source
)
SELECT
  'legacy_assessment',
  committee.id,
  '[' || COALESCE((
    SELECT group_concat(committee_member.person_id, ',')
    FROM committee_member
    WHERE committee_member.committee_id = committee.id
  ), '') || ']',
  '[' || COALESCE((
    SELECT group_concat(committee_member.id, ',')
    FROM committee_member
    WHERE committee_member.committee_id = committee.id
  ), '') || ']',
  '[' || COALESCE((
    SELECT group_concat(user_account.id, ',')
    FROM user_account
    WHERE user_account.person_id IN (
      SELECT committee_member.person_id
      FROM committee_member
      WHERE committee_member.committee_id = committee.id
    )
  ), '') || ']',
  'ready',
  '2026-01-01T00:00:00+00:00',
  'migration'
FROM committee;

INSERT INTO location
  (id, committee_id, name, street, postal_code, city, room)
VALUES
  (1, 1, 'Hof Athen (synthetisch)', 'Demoallee 1', '00000', 'Athen (Demo)', 'Saal Theseus'),
  (2, 1, 'Gartenbühne Athen (synthetisch)', 'Demoallee 2', '00000', 'Athen (Demo)', 'Bühne Hippolyta'),
  (3, 2, 'Lichtung Feenwald (synthetisch)', 'Fiktiver Waldpfad 1', '00000', 'Attischer Wald (Demo)', 'Lichtung Oberon');

INSERT INTO candidate
  (id, first_name, last_name, ihk_exam_number, specialization, training_company)
VALUES
  (1, 'Hermia', 'von Athen', 'ATHEN-DEMO-2026-0001', 'application_development', 'Atelier Athen (Demo)'),
  (2, 'Helena', 'von Athen', 'ATHEN-DEMO-2026-0002', 'system_integration', 'Werkstatt Athen (Demo)'),
  (3, 'Lysander', 'von Athen', 'ATHEN-DEMO-2026-0003', 'data_and_process_analysis', 'Kontor Athen (Demo)'),
  (4, 'Demetrius', 'von Athen', 'ATHEN-DEMO-2026-0004', 'digital_networking', 'Netzwerk Athen (Demo)'),
  (5, 'Egeus', 'von Athen', 'ATHEN-DEMO-2026-0005', 'application_development', 'Hofatelier Athen (Demo)'),
  (6, 'Philostrate', 'vom Hof', 'ATHEN-DEMO-2026-0006', 'system_integration', 'Hoforganisation Athen (Demo)'),
  (7, 'Peaseblossom', 'vom Feenwald', 'ATHEN-DEMO-2026-0007', 'application_development', 'Feenwerkstatt (Demo)'),
  (8, 'Cobweb', 'vom Feenwald', 'ATHEN-DEMO-2026-0008', 'system_integration', 'Feennetzwerk (Demo)'),
  (9, 'Moth', 'vom Feenwald', 'ATHEN-DEMO-2026-0009', 'data_and_process_analysis', 'Feenanalyse (Demo)'),
  (10, 'Mustardseed', 'vom Feenwald', 'ATHEN-DEMO-2026-0010', 'digital_networking', 'Feenverbindung (Demo)'),
  (11, 'Moonshine', 'vom Ensemble', 'ATHEN-DEMO-2026-0011', 'application_development', 'Theaterwerkstatt (Demo)'),
  (12, 'Lion', 'vom Ensemble', 'ATHEN-DEMO-2026-0012', 'system_integration', 'Bühnenbau Athen (Demo)');

INSERT INTO exam_half_year (id, season, year, status)
VALUES (1, 'winter', 2026, 'active');

INSERT INTO exam_round
  (id, exam_half_year_id, committee_id, name, status,
   availability_deadline, availability_reminder_at, created_by_member_id)
VALUES
  (1, 1, 1, 'Winter 2026/27', 'availability_requested',
   '2026-10-02 18:00:00', '2026-09-29 18:00:00', 1);

INSERT INTO round_candidate
  (id, exam_round_id, candidate_id, attempt_number, requires_mep)
VALUES
  (1, 1, 1, 1, 0),
  (2, 1, 2, 2, 1),
  (3, 1, 3, 1, 0),
  (4, 1, 4, 3, 0),
  (5, 1, 5, 2, 0),
  (6, 1, 6, 1, 1),
  (7, 1, 7, 3, 1),
  (8, 1, 8, 1, 0),
  (9, 1, 9, 2, 1),
  (10, 1, 10, 1, 0),
  (11, 1, 11, 1, 0),
  (12, 1, 12, 2, 0);

INSERT INTO candidate_committee_assignment
  (candidate_id, exam_half_year_id, exam_round_id, round_candidate_id)
SELECT candidate_id, 1, exam_round_id, id
FROM round_candidate;

INSERT INTO planning_settings
  (id, exam_round_id, calendar_week_from, calendar_week_to, exams_per_day,
   max_exam_days_per_week, lunch_break_enabled, default_location_id,
   updated_by_member_id)
VALUES
  (1, 1, '2026-W47', '2026-W49', 6, 3, 1, 1, 1);

INSERT INTO candidate_exam_day (id, exam_round_id, date)
VALUES
  (1, 1, '2026-11-16'),
  (2, 1, '2026-11-17'),
  (3, 1, '2026-11-18'),
  (4, 1, '2026-11-19'),
  (5, 1, '2026-11-20');

INSERT INTO member_availability
  (exam_round_id, committee_member_id, candidate_exam_day_id, availability, responded_at)
SELECT
  1,
  committee_member.id,
  candidate_exam_day.id,
  CASE
    WHEN committee_member.id IN (5, 7) THEN 'pending'
    WHEN candidate_exam_day.id = 3
      AND committee_member.id IN (2, 6) THEN 'afternoon'
    WHEN candidate_exam_day.id = 4
      AND committee_member.id IN (3, 8) THEN 'morning'
    ELSE 'full_day'
  END,
  CASE WHEN committee_member.id IN (5, 7) THEN NULL ELSE CURRENT_TIMESTAMP END
FROM committee_member
CROSS JOIN candidate_exam_day
WHERE committee_member.committee_id = 1
  AND candidate_exam_day.exam_round_id = 1;
