-- Generated by fixtures/generate.py. Do not edit directly.
-- Fixture profile: development
INSERT INTO committee (id, name, occupation, ihk, is_active, bootstrap_state)
VALUES
  (1, 'Hauptausschuss Athen', 'Fachinformatiker/in', 'Industrie- und Handelskammer Athen (Demo)', 1, 'ready'),
  (2, 'Fremdausschuss Feenwald', 'Fachinformatiker/in', 'Industrie- und Handelskammer Attischer Wald (Demo)', 1, 'ready');

INSERT INTO person (id, first_name, last_name, email, mobile)
VALUES
  (1, 'Theseus', 'von Athen', 'theseus.athen@demo.lzug.invalid', NULL),
  (2, 'Hippolyta', 'von Athen', 'hippolyta.athen@demo.lzug.invalid', NULL),
  (3, 'Peter', 'Quince', 'peter.quince@demo.lzug.invalid', NULL),
  (4, 'Robin', 'Goodfellow', 'robin.goodfellow@demo.lzug.invalid', NULL),
  (5, 'Nick', 'Bottom', 'nick.bottom@demo.lzug.invalid', NULL),
  (6, 'Francis', 'Flute', 'francis.flute@demo.lzug.invalid', NULL),
  (7, 'Tom', 'Snout', 'tom.snout@demo.lzug.invalid', NULL),
  (8, 'Snug', 'vom Ensemble', 'snug.ensemble@demo.lzug.invalid', NULL),
  (9, 'Oberon', 'vom Feenwald', 'oberon.feenwald@demo.lzug.invalid', NULL),
  (10, 'Titania', 'vom Feenwald', 'titania.feenwald@demo.lzug.invalid', NULL);

INSERT INTO committee_member
  (id, person_id, committee_id, member_status, committee_role, representing_side)
VALUES
  (1, 1, 1, 'ordinary', 'chair', 'employer'),
  (2, 2, 1, 'ordinary', 'deputy_chair', 'school'),
  (3, 3, 1, 'ordinary', 'member', 'employee'),
  (4, 4, 1, 'ordinary', 'member', 'employer'),
  (5, 5, 1, 'deputy', 'member', 'school'),
  (6, 6, 1, 'deputy', 'member', 'employee'),
  (7, 7, 1, 'deputy', 'member', 'employer'),
  (8, 8, 1, 'deputy', 'member', 'school'),
  (9, 9, 2, 'ordinary', 'chair', 'employer'),
  (10, 10, 2, 'ordinary', 'deputy_chair', 'employee'),
  (11, 4, 2, 'deputy', 'member', 'school');

INSERT INTO user_account (id, person_id, email, password_hash)
VALUES
  (1, 1, 'chair@demo.lzug.invalid', 'demo-password-hash'),
  (2, 3, 'examiner@demo.lzug.invalid', 'demo-password-hash'),
  (3, 2, 'deputy@demo.lzug.invalid', 'demo-password-hash'),
  (4, 6, 'replacement@demo.lzug.invalid', 'demo-password-hash');

INSERT INTO committee_admin_operation (
  operation_type, committee_id, person_ids_json, membership_ids_json,
  account_ids_json, result, occurred_at, technical_source
)
SELECT
  'legacy_assessment',
  committee.id,
  '[' || COALESCE((
    SELECT group_concat(committee_member.person_id, ',')
    FROM committee_member
    WHERE committee_member.committee_id = committee.id
  ), '') || ']',
  '[' || COALESCE((
    SELECT group_concat(committee_member.id, ',')
    FROM committee_member
    WHERE committee_member.committee_id = committee.id
  ), '') || ']',
  '[' || COALESCE((
    SELECT group_concat(user_account.id, ',')
    FROM user_account
    WHERE user_account.person_id IN (
      SELECT committee_member.person_id
      FROM committee_member
      WHERE committee_member.committee_id = committee.id
    )
  ), '') || ']',
  'ready',
  '2026-01-01T00:00:00+00:00',
  'migration'
FROM committee;

INSERT INTO exam_venue
  (id, scope, committee_id, name, normalized_name, street, postal_code, city,
   country, site_name, entrance, travel_directions, is_accessible,
   accessibility_status, accessibility_notes, latitude, longitude,
   coordinate_status, coordinate_source, is_active)
VALUES
  (1, 'global', NULL, 'Prüfungszentrum am Zappeion (Demo)', 'prüfungszentrum am zappeion (demo)', 'Vasilissis Olgas Avenue', '10557', 'Athens', 'Greece', 'Reale geografische Referenz: Zappeion Megaron, Athen', 'Synthetischer Demo-Eingang und Treffpunkt Theseus', 'Reale Orientierung: Bereich Zappeion, fußläufig von Syntagma. Der bezeichnete Eingang und Treffpunkt gehören ausschließlich zum synthetischen Prüfungsszenario.', 1, 'confirmed', 'Nur im synthetischen Prüfungsszenario als barrierefrei bewertet; keine Aussage über das reale Zappeion.', 37.971620, 23.736520, 'confirmed', 'Zappeion-Kontaktseite und OpenStreetMap-Referenz; https://www.zappeion.gr/en/contact.html; Abrufdatum: 2026-09-01', 0),
  (2, 'committee', 1, 'Prüfungswerkstätten Gazi (Demo)', 'prüfungswerkstätten gazi (demo)', 'Pireos 100', '11854', 'Athens', 'Greece', 'Reale geografische Referenz: Technopolis City of Athens', 'Synthetisches Demo-Tor und Treffpunkt Handwerkerensemble', 'Reale Orientierung: Metrostation Kerameikos und Pireos 100. Das bezeichnete Tor und der Treffpunkt gehören ausschließlich zum synthetischen Prüfungsszenario.', 1, 'confirmed', 'Nur im synthetischen Prüfungsszenario als barrierefrei bewertet; keine Aussage über die reale Technopolis.', 37.977779, 23.714099, 'confirmed', 'Technopolis City of Athens; https://www.athens-technopolis.gr/index.php/en/contact-us-eng; Abrufdatum: 2026-09-01', 0),
  (3, 'committee', 2, 'Prüfungsbereich Nationalgarten (Demo)', 'prüfungsbereich nationalgarten (demo)', 'Leoforos Vasilissis Amalias 1', '10557', 'Athens', 'Greece', 'Reale geografische Referenz: National Garden of Athens', 'Synthetischer Treffpunkt Feenwald', 'Reale Orientierung: Haupteingang an der Amalias-Allee und Umgebung Syntagma. Der bezeichnete Treffpunkt gehört ausschließlich zum synthetischen Prüfungsszenario.', 0, 'confirmed', 'Der für das Demo-Szenario angenommene Außenbereich besitzt unebene Wege und wird nicht als barrierefrei bewertet. Dies ist keine Aussage über den realen Nationalgarten.', 37.973365, 23.737690, 'confirmed', 'Stadt Athen, Nationalgarten; https://old.cityofathens.gr/episkeptes/aksiotheata/diadromes-stin-istoria-tis-athinas/o-kipos-tis-athinas; Abrufdatum: 2026-09-01', 0);

INSERT INTO exam_room
  (id, venue_id, name, normalized_name, access_notes, capacity, is_active)
VALUES
  (1, 1, 'Theseussaal', 'theseussaal', 'Synthetische Auffindung: ab Demo-Eingang dem Treffpunkt Theseus folgen.', 24, 1),
  (2, 2, 'Werkstatt Handwerkerensemble', 'werkstatt handwerkerensemble', 'Synthetische Auffindung: ab Demo-Tor dem Treffpunkt Handwerkerensemble folgen.', 18, 1),
  (3, 3, 'Lichtung Oberon', 'lichtung oberon', 'Synthetische Auffindung: ab Treffpunkt Feenwald der Demo-Beschilderung Oberon folgen.', 15, 1),
  (4, 1, 'Hippolytasaal', 'hippolytasaal', 'Synthetische Auffindung: ab Demo-Eingang dem Hinweis Hippolyta folgen.', 12, 1),
  (5, 2, 'Prüfhalle Pyramus', 'prüfhalle pyramus', 'Synthetische Auffindung: ab Demo-Tor dem Hinweis Pyramus folgen.', 30, 1),
  (6, 3, 'Lichtung Titania', 'lichtung titania', 'Synthetische Auffindung: ab Treffpunkt Feenwald der Demo-Beschilderung Titania folgen.', 15, 1);

UPDATE exam_venue
SET is_active = 1
WHERE id IN (1, 2, 3);

INSERT INTO exam_venue_contact
  (id, venue_id, label, role, phone, email, availability_notes, is_active)
VALUES
  (1, 1, 'Hippolyta von Athen', 'Synthetische Ortskoordination', NULL, 'hippolyta.athen@demo.lzug.invalid', 'Synthetischer Demo-Kontakt für den gesamten Prüfungsort.', 1),
  (2, 2, 'Peter Quince', 'Synthetische Raumkoordination', NULL, 'peter.quince@demo.lzug.invalid', 'Synthetischer Demo-Kontakt ausschließlich für die Werkstatt Handwerkerensemble.', 1);

INSERT INTO exam_venue_contact_room (contact_id, room_id)
VALUES
  (2, 2);


INSERT INTO candidate
  (id, first_name, last_name, ihk_exam_number, specialization, training_company)
VALUES
  (1, 'Hermia', 'von Athen', 'ATHEN-DEMO-2026-0001', 'application_development', 'Atelier Athen (Demo)'),
  (2, 'Helena', 'von Athen', 'ATHEN-DEMO-2026-0002', 'system_integration', 'Werkstatt Athen (Demo)'),
  (3, 'Lysander', 'von Athen', 'ATHEN-DEMO-2026-0003', 'data_and_process_analysis', 'Kontor Athen (Demo)'),
  (4, 'Demetrius', 'von Athen', 'ATHEN-DEMO-2026-0004', 'digital_networking', 'Netzwerk Athen (Demo)'),
  (5, 'Egeus', 'von Athen', 'ATHEN-DEMO-2026-0005', 'application_development', 'Hofatelier Athen (Demo)'),
  (6, 'Philostrate', 'vom Hof', 'ATHEN-DEMO-2026-0006', 'system_integration', 'Hoforganisation Athen (Demo)'),
  (7, 'Peaseblossom', 'vom Feenwald', 'ATHEN-DEMO-2026-0007', 'application_development', 'Feenwerkstatt (Demo)'),
  (8, 'Cobweb', 'vom Feenwald', 'ATHEN-DEMO-2026-0008', 'system_integration', 'Feennetzwerk (Demo)'),
  (9, 'Moth', 'vom Feenwald', 'ATHEN-DEMO-2026-0009', 'data_and_process_analysis', 'Feenanalyse (Demo)'),
  (10, 'Mustardseed', 'vom Feenwald', 'ATHEN-DEMO-2026-0010', 'digital_networking', 'Feenverbindung (Demo)'),
  (11, 'Moonshine', 'vom Ensemble', 'ATHEN-DEMO-2026-0011', 'application_development', 'Theaterwerkstatt (Demo)'),
  (12, 'Lion', 'vom Ensemble', 'ATHEN-DEMO-2026-0012', 'system_integration', 'Bühnenbau Athen (Demo)');

INSERT INTO exam_half_year (id, season, year, status)
VALUES (1, 'winter', 2026, 'active');

INSERT INTO exam_round
  (id, exam_half_year_id, committee_id, name, status,
   availability_deadline, availability_reminder_at, created_by_member_id)
VALUES
  (1, 1, 1, 'Winter 2026/27', 'availability_requested',
   '2026-10-02 18:00:00', '2026-09-29 18:00:00', 1);

INSERT INTO round_candidate
  (id, exam_round_id, candidate_id, attempt_number, requires_mep)
VALUES
  (1, 1, 1, 1, 0),
  (2, 1, 2, 2, 1),
  (3, 1, 3, 1, 0),
  (4, 1, 4, 3, 0),
  (5, 1, 5, 2, 0),
  (6, 1, 6, 1, 1),
  (7, 1, 7, 3, 1),
  (8, 1, 8, 1, 0),
  (9, 1, 9, 2, 1),
  (10, 1, 10, 1, 0),
  (11, 1, 11, 1, 0),
  (12, 1, 12, 2, 0);

INSERT INTO candidate_committee_assignment
  (candidate_id, exam_half_year_id, exam_round_id, round_candidate_id)
SELECT candidate_id, 1, exam_round_id, id
FROM round_candidate;

INSERT INTO planning_settings
  (id, exam_round_id, calendar_week_from, calendar_week_to, exams_per_day,
   max_exam_days_per_week, lunch_break_enabled, default_room_id,
   updated_by_member_id)
VALUES
  (1, 1, '2026-W47', '2026-W49', 6, 3, 1, 1, 1);

INSERT INTO candidate_exam_day (id, exam_round_id, date)
VALUES
  (1, 1, '2026-11-16'),
  (2, 1, '2026-11-17'),
  (3, 1, '2026-11-18'),
  (4, 1, '2026-11-19'),
  (5, 1, '2026-11-20');

INSERT INTO member_availability
  (exam_round_id, committee_member_id, candidate_exam_day_id, availability, responded_at)
SELECT
  1,
  committee_member.id,
  candidate_exam_day.id,
  CASE
    WHEN committee_member.id IN (5, 7) THEN 'pending'
    WHEN candidate_exam_day.id = 3
      AND committee_member.id IN (2, 6) THEN 'afternoon'
    WHEN candidate_exam_day.id = 4
      AND committee_member.id IN (3, 8) THEN 'morning'
    ELSE 'full_day'
  END,
  CASE WHEN committee_member.id IN (5, 7) THEN NULL ELSE CURRENT_TIMESTAMP END
FROM committee_member
CROSS JOIN candidate_exam_day
WHERE committee_member.committee_id = 1
  AND candidate_exam_day.exam_round_id = 1;
