-- Generated by scripts/generate_synthetic_fixtures.py. Do not edit directly.
INSERT INTO committee (id, name, occupation, ihk, is_active, bootstrap_state)
VALUES
  (1, 'Prüfungsausschuss Teststadt 1', 'Fachinformatiker/in', 'IHK Teststadt', 1, 'ready');

INSERT INTO person (id, first_name, last_name, email, mobile)
VALUES
  (1, 'Testperson', 'Alpha', 'testperson.alpha@example.invalid', '+49 000 0000001'),
  (2, 'Testperson', 'Beta', 'testperson.beta@example.invalid', '+49 000 0000002'),
  (3, 'Testperson', 'Gamma', 'testperson.gamma@example.invalid', '+49 000 0000003'),
  (4, 'Testperson', 'Delta', 'testperson.delta@example.invalid', '+49 000 0000004'),
  (5, 'Testperson', 'Epsilon', 'testperson.epsilon@example.invalid', '+49 000 0000005'),
  (6, 'Testperson', 'Zeta', 'testperson.zeta@example.invalid', '+49 000 0000006'),
  (7, 'Testperson', 'Eta', 'testperson.eta@example.invalid', '+49 000 0000007'),
  (8, 'Testperson', 'Theta', 'testperson.theta@example.invalid', '+49 000 0000008');

INSERT INTO committee_member
  (id, person_id, committee_id, member_status, committee_role, representing_side)
VALUES
  (1, 1, 1, 'ordinary', 'chair', 'employer'),
  (2, 2, 1, 'ordinary', 'deputy_chair', 'school'),
  (3, 3, 1, 'ordinary', 'member', 'employee'),
  (4, 4, 1, 'ordinary', 'member', 'employer'),
  (5, 5, 1, 'deputy', 'member', 'school'),
  (6, 6, 1, 'deputy', 'member', 'employee'),
  (7, 7, 1, 'deputy', 'member', 'employer'),
  (8, 8, 1, 'deputy', 'member', 'school');

INSERT INTO user_account (id, person_id, email, password_hash)
VALUES
  (1, 1, 'demo.alpha@example.invalid', 'demo-password-hash'),
  (2, 3, 'demo.gamma@example.invalid', 'demo-password-hash'),
  (3, 2, 'demo.beta@example.invalid', 'demo-password-hash');

INSERT INTO committee_admin_operation (
  operation_type, committee_id, person_ids_json, membership_ids_json,
  account_ids_json, result, occurred_at, technical_source
)
SELECT
  'legacy_assessment',
  committee.id,
  '[' || COALESCE((
    SELECT group_concat(committee_member.person_id, ',')
    FROM committee_member
    WHERE committee_member.committee_id = committee.id
  ), '') || ']',
  '[' || COALESCE((
    SELECT group_concat(committee_member.id, ',')
    FROM committee_member
    WHERE committee_member.committee_id = committee.id
  ), '') || ']',
  '[' || COALESCE((
    SELECT group_concat(user_account.id, ',')
    FROM user_account
    WHERE user_account.person_id IN (
      SELECT committee_member.person_id
      FROM committee_member
      WHERE committee_member.committee_id = committee.id
    )
  ), '') || ']',
  'ready',
  '2026-01-01T00:00:00+00:00',
  'migration'
FROM committee;

INSERT INTO location
  (id, committee_id, name, street, postal_code, city, room)
VALUES
  (1, 1, 'Prüfungszentrum Alpha (Test)', 'Testweg 1', '00000', 'Teststadt', 'Testraum A-01'),
  (2, 1, 'Prüfungszentrum Beta (Test)', 'Testweg 2', '00000', 'Teststadt', 'Testraum B-02');

INSERT INTO candidate
  (id, first_name, last_name, ihk_exam_number, specialization, training_company)
VALUES
  (1, 'Prüfling', 'Alpha', 'TEST-2026-0001', 'application_development', 'Testbetrieb Alpha'),
  (2, 'Prüfling', 'Beta', 'TEST-2026-0002', 'system_integration', 'Testbetrieb Beta'),
  (3, 'Prüfling', 'Gamma', 'TEST-2026-0003', 'data_and_process_analysis', 'Testbetrieb Gamma'),
  (4, 'Prüfling', 'Delta', 'TEST-2026-0004', 'digital_networking', 'Testbetrieb Delta'),
  (5, 'Prüfling', 'Epsilon', 'TEST-2026-0005', 'application_development', 'Testbetrieb Epsilon'),
  (6, 'Prüfling', 'Zeta', 'TEST-2026-0006', 'system_integration', 'Testbetrieb Zeta'),
  (7, 'Prüfling', 'Eta', 'TEST-2026-0007', 'application_development', 'Testbetrieb Eta'),
  (8, 'Prüfling', 'Theta', 'TEST-2026-0008', 'system_integration', 'Testbetrieb Theta'),
  (9, 'Prüfling', 'Iota', 'TEST-2026-0009', 'data_and_process_analysis', 'Testbetrieb Iota'),
  (10, 'Prüfling', 'Kappa', 'TEST-2026-0010', 'digital_networking', 'Testbetrieb Kappa'),
  (11, 'Prüfling', 'Lambda', 'TEST-2026-0011', 'application_development', 'Testbetrieb Lambda'),
  (12, 'Prüfling', 'My', 'TEST-2026-0012', 'system_integration', 'Testbetrieb My');

INSERT INTO exam_half_year (id, season, year, status)
VALUES (1, 'winter', 2026, 'active');

INSERT INTO exam_round
  (id, exam_half_year_id, committee_id, name, status,
   availability_deadline, availability_reminder_at, created_by_member_id)
VALUES
  (1, 1, 1, 'Winter 2026/27', 'availability_requested',
   '2026-10-02 18:00:00', '2026-09-29 18:00:00', 1);

INSERT INTO round_candidate
  (id, exam_round_id, candidate_id, attempt_number, requires_mep)
VALUES
  (1, 1, 1, 1, 0),
  (2, 1, 2, 2, 1),
  (3, 1, 3, 1, 0),
  (4, 1, 4, 3, 0),
  (5, 1, 5, 2, 0),
  (6, 1, 6, 1, 1),
  (7, 1, 7, 3, 1),
  (8, 1, 8, 1, 0),
  (9, 1, 9, 2, 1),
  (10, 1, 10, 1, 0),
  (11, 1, 11, 1, 0),
  (12, 1, 12, 2, 0);

INSERT INTO candidate_committee_assignment
  (candidate_id, exam_half_year_id, exam_round_id, round_candidate_id)
SELECT candidate_id, 1, exam_round_id, id
FROM round_candidate;

INSERT INTO planning_settings
  (id, exam_round_id, calendar_week_from, calendar_week_to, exams_per_day,
   max_exam_days_per_week, lunch_break_enabled, default_location_id,
   updated_by_member_id)
VALUES
  (1, 1, '2026-W47', '2026-W49', 6, 3, 1, 1, 1);

INSERT INTO candidate_exam_day (id, exam_round_id, date)
VALUES
  (1, 1, '2026-11-16'),
  (2, 1, '2026-11-17'),
  (3, 1, '2026-11-18'),
  (4, 1, '2026-11-19'),
  (5, 1, '2026-11-20');

INSERT INTO member_availability
  (exam_round_id, committee_member_id, candidate_exam_day_id, availability, responded_at)
SELECT
  1,
  committee_member.id,
  candidate_exam_day.id,
  CASE
    WHEN committee_member.id IN (5, 7) THEN 'pending'
    WHEN candidate_exam_day.id = 3 AND committee_member.id IN (2, 6) THEN 'afternoon'
    WHEN candidate_exam_day.id = 4 AND committee_member.id IN (3, 8) THEN 'morning'
    ELSE 'full_day'
  END,
  CASE WHEN committee_member.id IN (5, 7) THEN NULL ELSE CURRENT_TIMESTAMP END
FROM committee_member
CROSS JOIN candidate_exam_day
WHERE committee_member.committee_id = 1
  AND candidate_exam_day.exam_round_id = 1;
