#!/usr/bin/env python3
"""Generate layer-specific fixture adapters from the canonical synthetic data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "fixtures" / "synthetic-fixtures.json"
SQL_TARGET = ROOT / "db" / "seed_demo.sql"
TYPESCRIPT_TARGET = (
    ROOT / "frontend" / "src" / "app" / "testing" / "synthetic-fixtures.generated.ts"
)
PROTOTYPE_TARGET = (
    ROOT / "prototypes" / "pruefungsrunde-prototyp" / "synthetic-fixtures.generated.js"
)

SPECIALIZATION_LABELS = {
    "application_development": "Anwendungsentwicklung",
    "system_integration": "Systemintegration",
    "data_and_process_analysis": "Daten- und Prozessanalyse",
    "digital_networking": "Digitale Vernetzung",
}
MEMBER_STATUS_LABELS = {
    "ordinary": "Ordentliches Mitglied",
    "deputy": "Stellvertretendes Mitglied",
}
COMMITTEE_ROLE_LABELS = {
    "chair": "Vorsitz",
    "deputy_chair": "Stellvertretender Vorsitz",
    "member": "Mitglied",
}
REPRESENTING_SIDE_LABELS = {
    "employer": "Arbeitgeber",
    "employee": "Arbeitnehmer",
    "school": "Schule",
}


def load_source() -> dict[str, Any]:
    return json.loads(SOURCE.read_text(encoding="utf-8"))


def adapter_rows(data: dict[str, Any], group: str, adapter: str) -> list[dict[str, Any]]:
    return [row for row in data[group] if adapter in row["adapters"]]


def sql_value(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return str(int(value))
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def sql_rows(rows: list[list[Any]]) -> str:
    return ",\n".join("  (" + ", ".join(sql_value(value) for value in row) + ")" for row in rows)


def render_sql(data: dict[str, Any]) -> str:
    committees = adapter_rows(data, "committees", "seed")
    members = adapter_rows(data, "members", "seed")
    locations = adapter_rows(data, "locations", "seed")
    candidates = adapter_rows(data, "candidates", "seed")
    committee_rows = [[row["id"], row["name"], row["occupation"]] for row in committees]
    person_rows = [
        [
            row["person_id"],
            row["first_name"],
            row["last_name"],
            row["email"],
            row["mobile"],
        ]
        for row in members
    ]
    member_rows = [
        [
            row["id"],
            row["person_id"],
            row["committee_id"],
            row["member_status"],
            row["committee_role"],
            row["representing_side"],
        ]
        for row in members
    ]
    location_rows = [
        [
            row["id"],
            row["committee_id"],
            row["name"],
            row["street"],
            row["postal_code"],
            row["city"],
            row["room"],
        ]
        for row in locations
    ]
    candidate_rows = [
        [
            row["id"],
            row["first_name"],
            row["last_name"],
            row["ihk_exam_number"],
            row["specialization"],
            row["training_company"],
        ]
        for row in candidates
    ]
    round_candidate_rows = [
        [
            row["id"],
            1,
            row["id"],
            row["attempt_number"],
            row["requires_mep"],
        ]
        for row in candidates
    ]
    return f"""-- Generated by scripts/generate_synthetic_fixtures.py. Do not edit directly.
INSERT INTO committee (id, name, occupation)
VALUES
{sql_rows(committee_rows)};

INSERT INTO person (id, first_name, last_name, email, mobile)
VALUES
{sql_rows(person_rows)};

INSERT INTO committee_member
  (id, person_id, committee_id, member_status, committee_role, representing_side)
VALUES
{sql_rows(member_rows)};

INSERT INTO user_account (id, person_id, email, password_hash)
VALUES
  (1, 1, 'demo.alpha@example.invalid', 'demo-password-hash'),
  (2, 3, 'demo.gamma@example.invalid', 'demo-password-hash');

INSERT INTO location
  (id, committee_id, name, street, postal_code, city, room)
VALUES
{sql_rows(location_rows)};

INSERT INTO candidate
  (id, first_name, last_name, ihk_exam_number, specialization, training_company)
VALUES
{sql_rows(candidate_rows)};

INSERT INTO exam_half_year (id, season, year, status)
VALUES (1, 'winter', 2026, 'active');

INSERT INTO exam_round
  (id, exam_half_year_id, committee_id, name, status,
   availability_deadline, availability_reminder_at, created_by_member_id)
VALUES
  (1, 1, 1, 'Winter 2026/27', 'availability_requested',
   '2026-10-02 18:00:00', '2026-09-29 18:00:00', 1);

INSERT INTO round_candidate
  (id, exam_round_id, candidate_id, attempt_number, requires_mep)
VALUES
{sql_rows(round_candidate_rows)};

INSERT INTO candidate_committee_assignment
  (candidate_id, exam_half_year_id, exam_round_id, round_candidate_id)
SELECT candidate_id, 1, exam_round_id, id
FROM round_candidate;

INSERT INTO planning_settings
  (id, exam_round_id, calendar_week_from, calendar_week_to, exams_per_day,
   max_exam_days_per_week, lunch_break_enabled, default_location_id,
   updated_by_member_id)
VALUES
  (1, 1, '2026-W47', '2026-W49', 6, 3, 1, 1, 1);

INSERT INTO candidate_exam_day (id, exam_round_id, date)
VALUES
  (1, 1, '2026-11-16'),
  (2, 1, '2026-11-17'),
  (3, 1, '2026-11-18'),
  (4, 1, '2026-11-19'),
  (5, 1, '2026-11-20');

INSERT INTO member_availability
  (exam_round_id, committee_member_id, candidate_exam_day_id, availability, responded_at)
SELECT
  1,
  committee_member.id,
  candidate_exam_day.id,
  CASE
    WHEN committee_member.id IN (5, 7) THEN 'pending'
    WHEN candidate_exam_day.id = 3 AND committee_member.id IN (2, 6) THEN 'afternoon'
    WHEN candidate_exam_day.id = 4 AND committee_member.id IN (3, 8) THEN 'morning'
    ELSE 'full_day'
  END,
  CASE WHEN committee_member.id IN (5, 7) THEN NULL ELSE CURRENT_TIMESTAMP END
FROM committee_member
CROSS JOIN candidate_exam_day
WHERE committee_member.committee_id = 1
  AND candidate_exam_day.exam_round_id = 1;
"""


def render_typescript(data: dict[str, Any]) -> str:
    committees = [
        {key: value for key, value in row.items() if key != "adapters"}
        for row in adapter_rows(data, "committees", "frontend")
    ]
    members = []
    for row in adapter_rows(data, "members", "frontend"):
        member = {key: value for key, value in row.items() if key not in {"adapters", "response"}}
        member["email_verified_at"] = None
        if member["id"] == 2:
            member["committee_role"] = "member"
            member["is_active"] = 0
        members.append(member)
    locations = [
        {key: value for key, value in row.items() if key != "adapters"}
        for row in adapter_rows(data, "locations", "frontend")
    ]
    candidates = []
    for row in adapter_rows(data, "candidates", "frontend"):
        candidates.append(
            {
                "id": row["id"],
                "first_name": row["first_name"],
                "last_name": row["last_name"],
                "ihk_exam_number": row["ihk_exam_number"],
                "specialization": SPECIALIZATION_LABELS[row["specialization"]],
                "training_company": row["training_company"],
            }
        )
    payload = {
        "committees": committees,
        "members": members,
        "locations": locations,
        "candidates": candidates,
    }
    content = json.dumps(payload, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/generate_synthetic_fixtures.py. Do not edit directly.\n"
        f"export const syntheticFixtures = {content} as const;\n"
    )


def render_prototype(data: dict[str, Any]) -> str:
    members = []
    for row in adapter_rows(data, "members", "prototype"):
        members.append(
            {
                "id": row["id"],
                "firstName": row["first_name"],
                "lastName": row["last_name"],
                "status": MEMBER_STATUS_LABELS[row["member_status"]],
                "function": COMMITTEE_ROLE_LABELS[row["committee_role"]],
                "side": REPRESENTING_SIDE_LABELS[row["representing_side"]],
                "email": row["email"],
                "mobile": row["mobile"],
                "active": bool(row["is_active"]),
                "response": row["response"],
            }
        )
    candidates = []
    for row in adapter_rows(data, "candidates", "prototype"):
        candidates.append(
            {
                "id": row["id"],
                "firstName": row["first_name"],
                "lastName": row["last_name"],
                "examNo": row["ihk_exam_number"],
                "direction": SPECIALIZATION_LABELS[row["specialization"]],
                "company": row["training_company"],
                "attempt": row["attempt_number"],
                "mep": row["requires_mep"],
            }
        )
    locations = []
    for row in adapter_rows(data, "locations", "prototype"):
        locations.append(
            {
                "id": row["id"],
                "name": row["name"],
                "street": row["street"],
                "zip": row["postal_code"],
                "city": row["city"],
                "room": row["room"],
            }
        )
    payload = {"candidates": candidates, "members": members, "locations": locations}
    content = json.dumps(payload, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/generate_synthetic_fixtures.py. Do not edit directly.\n"
        f"globalThis.SYNTHETIC_FIXTURES = Object.freeze({content});\n"
    )


def outputs(data: dict[str, Any]) -> dict[Path, str]:
    return {
        SQL_TARGET: render_sql(data),
        TYPESCRIPT_TARGET: render_typescript(data),
        PROTOTYPE_TARGET: render_prototype(data),
    }


def generate(check: bool = False) -> list[Path]:
    mismatches = []
    for path, content in outputs(load_source()).items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                mismatches.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return mismatches


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when generated adapters do not match the canonical source",
    )
    args = parser.parse_args()
    mismatches = generate(check=args.check)
    if mismatches:
        for path in mismatches:
            print(f"outdated synthetic fixture adapter: {path.relative_to(ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
